# Use this netlify.toml OR configure manually in Netlify UI (recommended)
[build]
  base = "frontend"
  publish = "dist"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

# Frontend redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
